version: '3'

services:
  backend:
    build:
      context: ./src/backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./src/frontend
    volumes:
      - react-build:/src/frontend/build
  nginx:
    image: nginx:1.23-alpine 
    ports:
      - 80:8080
    volumes:
      - ./nginx/setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react-build:/var/www/frontend
    depends_on:
      - backend
      - frontend
  db:
    image: mongo:6.0-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test

volumes:
  react-build: